openapi: 3.2.0
info:
  title: Avalara AvaTax Provisioning API
  description: Welcome to the AvaTax API Postman Collection!
  version: 1.0.0
servers:
- url: http://{{baseurl}}
security:
- basicAuth: []
tags:
- name: Provisioning
paths:
  /api/v2/accounts/request:
    post:
      tags:
      - Provisioning
      summary: Avalara RequestNewAccount
      description: 'This API is for use by partner provisioning services customers only.


        Avalara invites select partners to refer new customers to the AvaTax service using the onboarding features

        of AvaTax. These partners can create accounts for new customers using this API.


        Calling this API creates an account with the specified product subscriptions, but does not configure billing.

        The customer will receive information from Avalara about how to configure billing for their account.

        You should call this API when a customer has requested to begin using Avalara services.


        If the newly created account owner wishes, they can confirm that they have read and agree to the Avalara

        terms and conditions. If they do so, they can receive a license key as part of this API and their

        API will be created in `Active` status. If the customer has not yet read and accepted these terms and

        conditions, the account will be created in `New` status and they can receive a license key by logging

        onto the AvaTax website and reviewing terms and conditions online.


        ### Security Policies


        * This API requires one of the following user roles: AccountAdmin, BatchServiceAdmin, CompanyAdmin, CSPTester, FirmAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.

        * This API is available by invitation only.

        * This API is available by invitation only. To request access to this feature, please speak to a business development manager and request access to [Provisioning:RequestNewAccount].'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                offer: DeveloperDotAvalaraFreeTrial
                connectorId: a0n4000000ChMwPAAV
                campaign: 70140000000TsVb
                leadSource: Direct Visitor
                accountName: BizTech Company Inc.
                website: https://biztech.com
                paymentMethodId: 701abc-def
                firstName: Bob
                lastName: Example
                email: bob@example.org
                username: bob
                welcomeEmail: Normal
                companyAddress:
                  line: 100 Ravine Ln
                  region: WA
                  country: US
                  postalCode: '98010'
                acceptAvalaraTermsAndConditions: true
                haveReadAvalaraTermsAndConditions: true
                marketingContext:
                  campaignId: 70140000000TsVb
                  leadSource: Direct Visitor
                accountType: Regular
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: postApiV2AccountsRequest
      x-operation-id-source: derived
  /api/v2/accounts/{id}/entitlements/{offer}:
    post:
      tags:
      - Provisioning
      summary: Avalara RequestNewEntitlement
      description: 'This API is for use by partner provisioning services customers only. This will allow the partners to allow

        the add new entitlement to an existing customer


        ### Security Policies


        * This API requires one of the following user roles: AccountAdmin, BatchServiceAdmin, CompanyAdmin, CSPTester, FirmAdmin, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.

        * This API is available by invitation only.

        * This API is available by invitation only. To request access to this feature, please speak to a business development manager and request access to [Provisioning:RequestNewAccount].'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: ''
      parameters:
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      - name: id
        in: path
        schema:
          type: string
        required: true
      - name: offer
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: postApiV2AccountsByIdEntitlementsByOffer
      x-operation-id-source: derived
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
