openapi: 3.2.0
info:
  title: Avalara AvaTax Distance Thresholds API
  description: Welcome to the AvaTax API Postman Collection!
  version: 1.0.0
servers:
- url: http://{{baseurl}}
security:
- basicAuth: []
tags:
- name: DistanceThresholds
paths:
  /api/v2/companies/{companyId}/distancethresholds:
    post:
      tags:
      - DistanceThresholds
      summary: Avalara CreateDistanceThreshold
      description: 'Create one or more DistanceThreshold objects for this company.


        A company-distance-threshold model indicates the distance between a company

        and the taxing borders of various countries. Distance thresholds are necessary

        to correctly calculate some value-added taxes.


        ### Security Policies


        * This API requires one of the following user roles: AccountAdmin, BatchServiceAdmin, CompanyAdmin, CSPAdmin, CSPTester, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 0
                companyId: 0
                originCountry: FR
                destinationCountry: BR
                thresholdExceeded: false
                type: Sale
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      - name: companyId
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: postApiV2CompaniesByCompanyIdDistancethresholds
      x-operation-id-source: derived
    get:
      tags:
      - DistanceThresholds
      summary: Avalara ListDistanceThresholds
      description: 'Lists all DistanceThreshold objects that belong to this company.


        A company-distance-threshold model indicates the distance between a company

        and the taxing borders of various countries. Distance thresholds are necessary

        to correctly calculate some value-added taxes.


        ### Security Policies


        * This API requires one of the following user roles: AccountAdmin, AccountUser, BatchServiceAdmin, CompanyAdmin, CompanyUser, CSPAdmin, CSPTester, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.'
      parameters:
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      - name: companyId
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiV2CompaniesByCompanyIdDistancethresholds
      x-operation-id-source: derived
  /api/v2/companies/{companyId}/distancethresholds/{id}:
    delete:
      tags:
      - DistanceThresholds
      summary: Avalara DeleteDistanceThreshold
      description: 'Marks the DistanceThreshold object identified by this URL as deleted.


        A company-distance-threshold model indicates the distance between a company

        and the taxing borders of various countries. Distance thresholds are necessary

        to correctly calculate some value-added taxes.


        ### Security Policies


        * This API requires one of the following user roles: AccountAdmin, BatchServiceAdmin, CompanyAdmin, CSPAdmin, CSPTester, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.'
      parameters:
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      - name: companyId
        in: path
        schema:
          type: string
        required: true
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: deleteApiV2CompaniesByCompanyIdDistancethresholdsById
      x-operation-id-source: derived
    get:
      tags:
      - DistanceThresholds
      summary: Avalara GetDistanceThreshold
      description: 'Retrieves a single DistanceThreshold object defined by this URL.


        A company-distance-threshold model indicates the distance between a company

        and the taxing borders of various countries. Distance thresholds are necessary

        to correctly calculate some value-added taxes.


        ### Security Policies


        * This API requires one of the following user roles: AccountAdmin, AccountUser, BatchServiceAdmin, CompanyAdmin, CompanyUser, CSPAdmin, CSPTester, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.'
      parameters:
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      - name: companyId
        in: path
        schema:
          type: string
        required: true
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiV2CompaniesByCompanyIdDistancethresholdsById
      x-operation-id-source: derived
    put:
      tags:
      - DistanceThresholds
      summary: Avalara UpdateDistanceThreshold
      description: 'Replace the existing DistanceThreshold object at this URL with an updated object.


        A company-distance-threshold model indicates the distance between a company

        and the taxing borders of various countries. Distance thresholds are necessary

        to correctly calculate some value-added taxes.


        All data from the existing object will be replaced with data in the object you PUT.

        To set a field''s value to null, you may either set its value to null or omit that field from the object you post.


        ### Security Policies


        * This API requires one of the following user roles: AccountAdmin, BatchServiceAdmin, CompanyAdmin, CSPAdmin, CSPTester, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 0
                companyId: 0
                originCountry: FR
                destinationCountry: BR
                thresholdExceeded: false
                type: Sale
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      - name: companyId
        in: path
        schema:
          type: string
        required: true
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: putApiV2CompaniesByCompanyIdDistancethresholdsById
      x-operation-id-source: derived
  /api/v2/distancethresholds:
    get:
      tags:
      - DistanceThresholds
      summary: Avalara QueryDistanceThresholds
      description: 'Lists all DistanceThreshold objects that belong to this account.


        A company-distance-threshold model indicates the distance between a company

        and the taxing borders of various countries. Distance thresholds are necessary

        to correctly calculate some value-added taxes.


        Search for specific objects using the criteria in the `$filter` parameter; full documentation is available on Filtering in REST .

        Paginate your results using the `$top`, `$skip`, and `$orderby` parameters.


        ### Security Policies


        * This API requires one of the following user roles: AccountAdmin, AccountUser, BatchServiceAdmin, CompanyAdmin, CompanyUser, CSPAdmin, CSPTester, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.'
      parameters:
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiV2Distancethresholds
      x-operation-id-source: derived
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
