openapi: 3.2.0
info:
  title: Avalara AvaTax Notifications API
  description: Welcome to the AvaTax API Postman Collection!
  version: 1.0.0
servers:
- url: http://{{baseurl}}
security:
- basicAuth: []
tags:
- name: Notifications
paths:
  /api/v2/notifications/{id}/dismiss:
    put:
      tags:
      - Notifications
      summary: Avalara DismissNotification
      description: 'Marks the notification identified by this URL as dismissed.


        A notification is a message from Avalara that may have relevance to your business. You may want

        to regularly review notifications and then dismiss them when you are certain that you have addressed

        any relevant concerns raised by this notification.


        An example of a notification would be a message about new software, or a change to AvaTax that may

        affect you, or a potential issue with your company''s tax profile.


        When you dismiss a notification, the notification will track the user and time when it was

        dismissed. You can then later review which employees of your company dismissed notifications to

        determine if they were resolved appropriately.


        A Global notification with null accountId and companyId cannot be dismissed and will expire within a given time span.


        ### Security Policies


        * This API requires one of the following user roles: AccountAdmin, AccountUser, BatchServiceAdmin, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPAdmin, CSPTester, ECMAccountUser, ECMCompanyUser, FirmAdmin, FirmUser, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: ''
      parameters:
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: putApiV2NotificationsByIdDismiss
      x-operation-id-source: derived
  /api/v2/notifications/{id}:
    get:
      tags:
      - Notifications
      summary: Avalara GetNotification
      description: 'Retrieve a single notification by its unique ID number.


        A notification is a message from Avalara that may have relevance to your business. You may want

        to regularly review notifications and then dismiss them when you are certain that you have addressed

        any relevant concerns raised by this notification.


        An example of a notification would be a message about new software, or a change to AvaTax that may

        affect you, or a potential issue with your company''s tax profile.


        ### Security Policies


        * This API requires one of the following user roles: AccountAdmin, AccountOperator, AccountUser, BatchServiceAdmin, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPAdmin, CSPTester, ECMAccountUser, ECMCompanyUser, FirmAdmin, FirmUser, ProStoresOperator, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.'
      parameters:
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiV2NotificationsById
      x-operation-id-source: derived
  /api/v2/notifications:
    get:
      tags:
      - Notifications
      summary: Avalara ListNotifications
      description: 'List all notifications.


        A notification is a message from Avalara that may have relevance to your business. You may want

        to regularly review notifications and then dismiss them when you are certain that you have addressed

        any relevant concerns raised by this notification.


        An example of a notification would be a message about new software, or a change to AvaTax that may

        affect you, or a potential issue with your company''s tax profile.


        You may search for specific objects using the criteria in the `$filter` parameter; full documentation is available on Filtering in REST .

        Paginate your results using the `$top`, `$skip`, and `$orderby` parameters.


        ### Security Policies


        * This API requires one of the following user roles: AccountAdmin, AccountOperator, AccountUser, BatchServiceAdmin, CompanyAdmin, CompanyUser, Compliance Root User, ComplianceAdmin, ComplianceUser, CSPAdmin, CSPTester, ECMAccountUser, ECMCompanyUser, FirmAdmin, FirmUser, ProStoresOperator, Registrar, SiteAdmin, SSTAdmin, SystemAdmin, TechnicalSupportAdmin, TechnicalSupportUser, TreasuryAdmin, TreasuryUser.'
      parameters:
      - name: X-Avalara-Client
        in: header
        schema:
          type: string
        description: Identifies the software you are using to call this API. For more information on the client header, see [Client Headers](https://developer.avalara.com/avatax/client-headers/).
        example: AvaTax Postman Collection
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiV2Notifications
      x-operation-id-source: derived
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
